# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
# test
version: 2.1

orbs:
  python: circleci/python@2.1.1

# Define a job to be invoked later in a workflow.
jobs:
  build_and_test: # this can be any name you choose
    executor: python/default # use the default executor defined within the orb
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install dolphot 
          command: cd example; for f in tar.gz ACS.tar.gz WFC3.tar.gz WFPC2.tar.gz Roman.tar.gz; do wget http://americano.dolphinsim.com/dolphot/dolphot2.0."$f"; done; for f in *.tar.gz; do tar xf "$f"; done; patch < Makefile_diff.patch; patch < dolphot_common_diff.patch; cd dolphot2.0; make
      - run:
          name: Run tests
          command: python -m testing
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

# Orchestrate jobs using workflows
workflows:
  build_test_deploy:
    jobs:
      - build_and_test

